apiVersion: v1
kind: LimitRange
metadata:
  name: agent-defaults
  namespace: {{ .Release.Namespace }}
spec:
  limits:
    - type: Container
      default:
        memory: {{ .Values.limitRange.defaultMemory }}
      defaultRequest:
        cpu: {{ .Values.limitRange.defaultRequestCpu }}
        memory: {{ .Values.limitRange.defaultRequestMemory }}
      max:
        memory: {{ .Values.limitRange.maxMemory }}
